site_name: "Biosignal Dataset"
site_url: "https://sangjinYoon.github.io/biosignal-site/"
repo_url: "https://github.com/sangjinYoon/biosignal-site"
repo_name: "biosignal-site"

theme:
  name: material
  language: ko
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 다크 모드
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 라이트 모드
  font:
    text: Noto Sans KR
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: ko

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - ECG:
    - ECG Overview: ecg/index.md
    - Apnea Dataset: ecg/apnea-dataset.md
    - BIDMC Congestive Heart Failure Database: ecg/bidmc-congestive-heart-failure-database.md
    - Cardiologist: ecg/cardiologist.md
    - Chapman Shaoxing: ecg/chapman-shaoxing.md
    - CODE 15% ECG Dataset: ecg/code-15-ecg-dataset.md
    - ECG-ID Database: ecg/ecg-id-database.md
    - ECG5000 Dataset: ecg/ecg5000-dataset.md
    - ECGFM-KED Clinical Dataset: ecg/ecgfm-ked-clinical-dataset.md
    - European ST-T Database: ecg/european-st-t-database.md
    - Fantasia: ecg/fantasia.md
    - IKEM ECG Dataset: ecg/ikem-ecg-dataset.md
    - Long-Term AF Database: ecg/long-term-af-database.md
    - Long-term ST Database: ecg/long-term-st-database.md
    - LUDB: ecg/ludb.md
    - MIMIC-IV-ECG: ecg/mimic-iv-ecg.md
    - MIT-BIH Arrythmia database: ecg/mit-bih-arrythmia-database.md
    - MIT-BIH Atrial Fibrillation: ecg/mit-bih-atrial-fibrillation.md
    - MIT-BIH Long-Term ECG Database: ecg/mit-bih-long-term-ecg-database.md
    - MIT-BIH Malignant Ventricular Ectopy Database: ecg/mit-bih-malignant-ventricular-ectopy-database.md
    - MIT-BIH Noise Stress Test Database: ecg/mit-bih-noise-stress-test-database.md
    - MIT-BIH Normal Sinus Rhythm Database: ecg/mit-bih-normal-sinus-rhythm-database.md
    - MIT-BIH ST Change Database: ecg/mit-bih-st-change-database.md
    - MIT-BIH supraventricular arrhythmia database: ecg/mit-bih-supraventricular-arrhythmia-database.md
    - music-sudden-cardiac-death-in-chronic-heart-failur: ecg/music-sudden-cardiac-death-in-chronic-heart-failur.md
    - NINGBO: ecg/ningbo.md
    - PhysioNet 2017: ecg/physionet-2017.md
    - PhysioNet Challenge 2020: ecg/physionet-challenge-2020.md
    - QT Database: ecg/qt-database.md
    - SaMi-Trop ECG Dataset: ecg/sami-trop-ecg-dataset.md
    - SensSmartTech Dataset: ecg/senssmarttech-dataset.md
    - SHDB-AF: ecg/shdb-af.md
    - Sudden Cardiac Death Holter Database: ecg/sudden-cardiac-death-holter-database.md
  - EEG:
    - EEG Overview: eeg/index.md
    - EEG Dataset (상세): eeg/eeg-dataset-2.md
    - 2018 Physionnet Challenge: eeg/2018-physionnet-challenge.md
    - BCI IV-1: eeg/bci-iv-1.md
    - BCI IV-2a: eeg/bci-iv-2a.md
    - BCI IV-2b: eeg/bci-iv-2b.md
    - BCI-NER Challenge: eeg/bci-ner-challenge.md
    - BCI2020-3: eeg/bci2020-3.md
    - Berlin (dsr): eeg/berlin-dsr.md
    - Berlin (nback): eeg/berlin-nback.md
    - Berlin (wg): eeg/berlin-wg.md
    - CHB-MIT: eeg/chb-mit.md
    - DEAP: eeg/deap.md
    - DREAMER: eeg/dreamer.md
    - Emobrain: eeg/emobrain.md
    - Fatigueset: eeg/fatigueset.md
    - Grasp and Lift Challenge: eeg/grasp-and-lift-challenge.md
    - HCI-Tagging (Emotion): eeg/hci-tagging-emotion.md
    - HCI-Tagging (ERP): eeg/hci-tagging-erp.md
    - High Gamma: eeg/high-gamma.md
    - Inria BCI Challenge: eeg/inria-bci-challenge.md
    - ISRUC Sleep: eeg/isruc-sleep.md
    - Mental Arithmetic: eeg/mental-arithmetic.md
    - MoBI: eeg/mobi.md
    - Mumtaz2016: eeg/mumtaz2016.md
    - Neonate: eeg/neonate.md
    - NMT(Events): eeg/nmtevents.md
    - NMT(Scalp-EEG): eeg/nmtscalp-eeg.md
    - Physionet MI EEG: eeg/physionet-mi-eeg.md
    - Raw EEG Data: eeg/raw-eeg-data.md
    - Resting State EEG Data: eeg/resting-state-eeg-data.md
    - SEED: eeg/seed.md
    - SEED-IV: eeg/seed-iv.md
    - SEED-V: eeg/seed-v.md
    - SHU-MI: eeg/shu-mi.md
    - Siena: eeg/siena.md
    - Sleep-EDF: eeg/sleep-edf.md
    - SPIS Resting State Dataset: eeg/spis-resting-state-dataset.md
    - Stew: eeg/stew.md
    - Target Versus Non Target: eeg/target-versus-non-target.md
    - TUAB: eeg/tuab.md
    - TUEG: eeg/tueg.md
    - TUEV: eeg/tuev.md
    - TUSL: eeg/tusl.md
    - TUSZ: eeg/tusz.md
  - EMG:
    - EMG Overview: emg/index.md
    - BioPatRec: emg/biopatrec.md
    - Camargo, et al: emg/camargo-et-al.md
    - CapgMyo-db: emg/capgmyo-db.md
    - EMG data VR: emg/emg-data-vr.md
    - EMG-EPN-12: emg/emg-epn-12.md
    - EMG-UKA: emg/emg-uka.md
    - ENABL3S: emg/enabl3s.md
    - FlexWear: emg/flexwear.md
    - FSC: emg/fsc.md
    - Human kinematic-kinetic EMG: emg/human-kinematic-kinetic-emg.md
    - Hyser: emg/hyser.md
    - MCS: emg/mcs.md
    - NinaproDB: emg/ninaprodb.md
    - PME4: emg/pme4.md
    - R V Schulte et al: emg/r-v-schulte-et-al.md
    - SeNic: emg/senic.md
    - SIAT-LLMD: emg/siat-llmd.md
    - Silent speech: emg/silent-speech.md
    - UCI EMG Data for Gestures: emg/uci-emg-data-for-gestures.md
    - UCI EMG dataset in lower limb: emg/uci-emg-dataset-in-lower-limb.md
    - UCI-sEMG for basic hand movements: emg/uci-semg-for-basic-hand-movements.md
